### ISSUE TITLE
base64 data appears to be truncated

### ISSUE THREAD

**Issue by oreporan** [adriangodong/githubjwt#6]
I'm using `StringPrivateKeySource` and I feed it a valid pem that I got from github.
However it fails with the error:

```
System.IO.IOException: base64 data appears to be truncated
   at Org.BouncyCastle.Utilities.IO.Pem.PemReader.LoadObject(String type)
   at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()
   at GitHubJwt.GitHubJwtFactory.GetPrivateKey()
   at GitHubJwt.GitHubJwtFactory.CreateEncodedJwtToken()
   at Miro.Services.Auth.InstallationTokenStore.GetInstallationToken(String pemData, String githubInstallationId) in /app/Services/Auth/InstallationTokenStore.cs:line 71
   at System.Reactive.Subjects.AsyncSubject`1.GetResult() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\AsyncSubject.cs:line 439
```

This is the code
```C#
var pemBase64Decoded = Encoding.UTF8.GetString(Convert.FromBase64String(pemVar));
var generator = new GitHubJwt.GitHubJwtFactory(new StringPrivateKeySource(pemData),
                                                           new GitHubJwtFactoryOptions
                                                           {
                                                               AppIntegrationId = 15348,
                                                               ExpirationSeconds = 600 // 10 minutes is the maximum time allowed
                                                           });

var jwtToken = generator.CreateEncodedJwtToken(); // Fails here
```

I'm using StringPrivateKeySource because I load it from an env var as base64, and decode it on my side into `pemBase64Decoded`

I've validated that the decoded base64 is identical to the pem

**Comment by oreporan** [comment]
I'm looking at the test, but can't understand what format you used here - 
https://github.com/adriangodong/githubjwt/blob/master/GitHubJwt.Tests/envvar.pem

**Comment by oreporan** [comment]
You should document that its the `pem` without the `----BEGIN` and `-----END`

**Comment by evolutionise** [comment]
Hit the same issue - agree that documenting it would be helpful.
