### ISSUE TITLE
This library doesnt support private keys with headers

### ISSUE THREAD

**Issue by shaybenh7** [adriangodong/githubjwt#85]
Hey,
when I'm trying to create my JWT with my private key that contains the headers:
-----BEGIN RSA PRIVATE KEY-----
 and
-----END RSA PRIVATE KEY----- 
it gets an exception:
System.IO.IOException: END RSA PRIVATE KEY was not found.
   at Org.BouncyCastle.Utilities.IO.Pem.PemReader.ReadPemObject()
   at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()

when removing it, it works.
would you be able to fix it?

**Comment by shaybenh7** [comment]
please review
https://github.com/adriangodong/githubjwt/pull/86
